# vim ft=yaml
language: python

env:
  global:
    - DEPENDS="requirements.txt"
    - COVERAGE=1

python:
  - 3.4
  - 2.7

before_install:
  - source tools/travis_tools.sh
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python --version
  - pip install --upgrade pip
  - sudo apt-get install libblas-dev liblapack-dev libatlas3gf-base
  - wheelhouse_pip_r_install ${DEPENDS}

install:
  - python setup.py install
  - cd doc && make html && cd ..

script:
  - make coverage

after_success:
  - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
