# vim ft=yaml
language: python

env:
  global:
    - DEPENDS="numpy scipy matplotlib ipython"
    - COVERAGE=1

python:
  - 3.4
  - 2.7

before_install:
  - source tools/travis_tools.sh
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python --version # just to check
  - retry pip install nose # always
  - sudo apt-get install libblas-dev liblapack-dev libatlas3gf-base
  - cd doc && pip install -r requirements.txt && cd ..
  - wheelhouse_pip_install ${DEPENDS}
  - if [ "${COVERAGE}" == "1" ]; then
    pip install coverage;
    pip install coveralls;
    fi

install:
  - python setup.py install
  - cd doc && make html && cd ..

script:
  - make coverage

after_success:
  - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
