# vim ft=yaml
language: python

env:
  global:
    - DEPENDS="numpy scipy matplotlib"
    - COVERAGE=1

python:
  - 3.4
  - 2.7

before_install:
  - sudo apt-get update
  - source tools/travis_tools.sh
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python --version # just to check
  - retry pip install nose # always
  - sudo apt-get install libblas-dev liblapack-dev libatlas3gf-base
  - wheelhouse_pip_install ${DEPENDS}
  - if [ "${COVERAGE}" == "1" ]; then
    pip install coverage;
    pip install coveralls;
    fi

install:
  - python setup.py install

script:
  - make test

after_success:
  - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
